 const product = [
  {
    id: 1,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 2,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 3,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 4,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 5,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 6,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },

  {
    id: 7,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: "70%",
    type: "flash",
  },
  {
    id: 8,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 9,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 10,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: "30%",
    type: "flash",
  },
  {
    id: 11,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 12,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: "40%",
    type: "flash",
  },
  {
    id: 13,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 14,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: "50%",
    type: "flash",
  },
  {
    id: 15,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
  {
    id: 16,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Training Sports Vintage",
    price: "₦ 11,600",
    oldPrice: "₦ 11,600",
    rating: 4,
    category: false,
    off: " ",
    type: "",
  },
];

export default product

export const category = [
  {
    id: 1,
    image: "@/assets/images/demo/1.png",
    name: "Phone & Tablets",
    category: true,
  },
  {
    id: 2,
    image: "@/assets/images/demo/1.png",
    name: "Computers & Accessories",
    category: true,
  },
  {
    id: 3,
    image: "@/assets/images/demo/1.png",
    name: "Men’s Clothing",
    category: true,
  },
  {
    id: 4,
    image: "@/assets/images/demo/1.png",
    name: "Shoes",
    category: true,
  },
  {
    id: 5,
    image: "@/assets/images/demo/1.png",
    name: "Mobile Accessories",
    category: true,
  },
  {
    id: 6,
    image: "@/assets/images/demo/1.png",
    name: "Automotive and Tools",
    category: true,
  },
  {
    id: 7,
    image: "@/assets/images/demo/1.png",
    name: "Beauty and Personal Care",
    category: true,
  },
  {
    id: 8,
    image: "@/assets/images/demo/1.png",
    name: "Books and Stationery",
    category: true,
  },
  {
    id: 9,
    image: "@/assets/images/demo/1.png",
    name: "Clothing and Fashion",
    category: true,
  },
  {
    id: 10,
    image: "@/assets/images/demo/1.png",
    name: "Electronics",
    category: true,
  },
  {
    id: 11,
    image: "@/assets/images/demo/1.png",
    name: "Health and Wellness",
    category: true,
  },
  {
    id: 12,
    image: "@/assets/images/demo/1.png",
    name: "Home and Living",
    category: true,
  },
  {
    id: 13,
    image: "@/assets/images/demo/1.png",
    name: "Pets and Pet Supplies",
    category: true,
  },
  {
    id: 14,
    image: "@/assets/images/demo/1.png",
    name: "Sports and Outdoors",
    category: true,
  },
  {
    id: 15,
    image: "@/assets/images/demo/1.png",
    name: "Toys and Games",
    category: true,
  },
];


export const ads = [
  {
    store: "Tech Haven",
    title: "Premium Gadgets Sale",
    brief: "Get 30% off on all smart phones and accessories this week only!",
    image: require("@/assets/images/demo/popular-ads1.png"),
    url: "https://example.com/tech-sale",
  },
  {
    store: "Fashion Boutique",
    title: "Summer Collection Launch",
    brief: "New arrivals for summer 2023 - limited stock available!",
    image: require("@/assets/images/demo/popular-ads2.png"),
    url: "https://example.com/summer-fashion",
  },
  {
    store: "Home Essentials",
    title: "Kitware Warehouse Clearance",
    brief: "Up to 50% off on cookware and kitchen appliances",
    image: require("@/assets/images/demo/popular-ads1.png"),
    url: "https://example.com/kitchen-warehouse",
  },
  {
    store: "Fitness Pro",
    title: "Home Gym Equipment Bundle",
    brief: "Complete home gym setup with free delivery and installation",
    image: require("@/assets/images/demo/popular-ads2.png"),
    url: "https://example.com/home-gym",
  }
];